version: '3.7'

services:
  web_summit:
    build: .
    container_name: qdrant_demo_web_summit
    ports:
      - 8005:8000
    environment:
      - QDRANT_HOST=qdrant_web_summit
    depends_on:
      - qdrant_web_summit
    networks:
      - qdrant-net
    volumes:
      - ./data/startups_websummit.sqlite3:/code/data/startups_websummit.sqlite3
  qdrant_web_summit:
    image: generall/qdrant:v0.4.2
#    mem_limit: 450m
#    ports:
#    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
