# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.match import Match
globals()['Match'] = Match
from openapi_client.model.condition_any_of1 import ConditionAnyOf1


class TestConditionAnyOf1(unittest.TestCase):
    """ConditionAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionAnyOf1(self):
        """Test ConditionAnyOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionAnyOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
