# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.condition import Condition
globals()['Condition'] = Condition
from openapi_client.model.filter import Filter


class TestFilter(unittest.TestCase):
    """Filter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilter(self):
        """Test Filter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Filter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
