# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_ops import PayloadOps
from openapi_client.model.payload_ops_any_of1_delete_payload import PayloadOpsAnyOf1DeletePayload
from openapi_client.model.payload_ops_any_of2_clear_payload import PayloadOpsAnyOf2ClearPayload
from openapi_client.model.payload_ops_any_of_set_payload import PayloadOpsAnyOfSetPayload
from openapi_client.model.point_insert_ops import PointInsertOps
from openapi_client.model.point_ops import PointOps
from openapi_client.model.point_ops_any_of1_delete_points import PointOpsAnyOf1DeletePoints
globals()['PayloadOps'] = PayloadOps
globals()['PayloadOpsAnyOf1DeletePayload'] = PayloadOpsAnyOf1DeletePayload
globals()['PayloadOpsAnyOf2ClearPayload'] = PayloadOpsAnyOf2ClearPayload
globals()['PayloadOpsAnyOfSetPayload'] = PayloadOpsAnyOfSetPayload
globals()['PointInsertOps'] = PointInsertOps
globals()['PointOps'] = PointOps
globals()['PointOpsAnyOf1DeletePoints'] = PointOpsAnyOf1DeletePoints
from openapi_client.model.collection_update_operations import CollectionUpdateOperations


class TestCollectionUpdateOperations(unittest.TestCase):
    """CollectionUpdateOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionUpdateOperations(self):
        """Test CollectionUpdateOperations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CollectionUpdateOperations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
