# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.points_api import PointsApi  # noqa: E501


class TestPointsApi(unittest.TestCase):
    """PointsApi unit test stubs"""

    def setUp(self):
        self.api = PointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_point(self):
        """Test case for get_point

        Retrieve point by id  # noqa: E501
        """
        pass

    def test_get_points(self):
        """Test case for get_points

        Retrieve points by ids  # noqa: E501
        """
        pass

    def test_search_points(self):
        """Test case for search_points

        Search points  # noqa: E501
        """
        pass

    def test_update_points(self):
        """Test case for update_points

        Update points in collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
