# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.distance import Distance
globals()['Distance'] = Distance
from openapi_client.model.storage_ops_any_of_create_collection import StorageOpsAnyOfCreateCollection


class TestStorageOpsAnyOfCreateCollection(unittest.TestCase):
    """StorageOpsAnyOfCreateCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageOpsAnyOfCreateCollection(self):
        """Test StorageOpsAnyOfCreateCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageOpsAnyOfCreateCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
