# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.storage_ops_any_of import StorageOpsAnyOf
from openapi_client.model.storage_ops_any_of1 import StorageOpsAnyOf1
from openapi_client.model.storage_ops_any_of2 import StorageOpsAnyOf2
from openapi_client.model.storage_ops_any_of2_change_aliases import StorageOpsAnyOf2ChangeAliases
from openapi_client.model.storage_ops_any_of_create_collection import StorageOpsAnyOfCreateCollection
globals()['StorageOpsAnyOf'] = StorageOpsAnyOf
globals()['StorageOpsAnyOf1'] = StorageOpsAnyOf1
globals()['StorageOpsAnyOf2'] = StorageOpsAnyOf2
globals()['StorageOpsAnyOf2ChangeAliases'] = StorageOpsAnyOf2ChangeAliases
globals()['StorageOpsAnyOfCreateCollection'] = StorageOpsAnyOfCreateCollection
from openapi_client.model.storage_ops import StorageOps


class TestStorageOps(unittest.TestCase):
    """StorageOps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageOps(self):
        """Test StorageOps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageOps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
