# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_ops_any_of2_clear_payload import PayloadOpsAnyOf2ClearPayload
globals()['PayloadOpsAnyOf2ClearPayload'] = PayloadOpsAnyOf2ClearPayload
from openapi_client.model.payload_ops_any_of2 import PayloadOpsAnyOf2


class TestPayloadOpsAnyOf2(unittest.TestCase):
    """PayloadOpsAnyOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadOpsAnyOf2(self):
        """Test PayloadOpsAnyOf2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadOpsAnyOf2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
