# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.point_ops_any_of1_delete_points import PointOpsAnyOf1DeletePoints


class TestPointOpsAnyOf1DeletePoints(unittest.TestCase):
    """PointOpsAnyOf1DeletePoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointOpsAnyOf1DeletePoints(self):
        """Test PointOpsAnyOf1DeletePoints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointOpsAnyOf1DeletePoints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
