# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.range import Range
globals()['Range'] = Range
from openapi_client.model.condition_any_of2 import ConditionAnyOf2


class TestConditionAnyOf2(unittest.TestCase):
    """ConditionAnyOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionAnyOf2(self):
        """Test ConditionAnyOf2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionAnyOf2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
