# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alias_operations import AliasOperations
globals()['AliasOperations'] = AliasOperations
from openapi_client.model.storage_ops_any_of2_change_aliases import StorageOpsAnyOf2ChangeAliases


class TestStorageOpsAnyOf2ChangeAliases(unittest.TestCase):
    """StorageOpsAnyOf2ChangeAliases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageOpsAnyOf2ChangeAliases(self):
        """Test StorageOpsAnyOf2ChangeAliases"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageOpsAnyOf2ChangeAliases()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
