# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_type import PayloadType
globals()['PayloadType'] = PayloadType
from openapi_client.model.record import Record


class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecord(self):
        """Test Record"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Record()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
