# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_ops_any_of2_clear_payload import PayloadOpsAnyOf2ClearPayload


class TestPayloadOpsAnyOf2ClearPayload(unittest.TestCase):
    """PayloadOpsAnyOf2ClearPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadOpsAnyOf2ClearPayload(self):
        """Test PayloadOpsAnyOf2ClearPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadOpsAnyOf2ClearPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
