# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indexes_any_of import IndexesAnyOf
from openapi_client.model.indexes_any_of1 import IndexesAnyOf1
from openapi_client.model.indexes_any_of1_options import IndexesAnyOf1Options
globals()['IndexesAnyOf'] = IndexesAnyOf
globals()['IndexesAnyOf1'] = IndexesAnyOf1
globals()['IndexesAnyOf1Options'] = IndexesAnyOf1Options
from openapi_client.model.indexes import Indexes


class TestIndexes(unittest.TestCase):
    """Indexes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndexes(self):
        """Test Indexes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Indexes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
