# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.geo_bounding_box import GeoBoundingBox
globals()['GeoBoundingBox'] = GeoBoundingBox
from openapi_client.model.condition_any_of3 import ConditionAnyOf3


class TestConditionAnyOf3(unittest.TestCase):
    """ConditionAnyOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionAnyOf3(self):
        """Test ConditionAnyOf3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionAnyOf3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
