# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.collections_api import CollectionsApi  # noqa: E501


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_collection(self):
        """Test case for get_collection

        Get information about existing collection  # noqa: E501
        """
        pass

    def test_get_collections(self):
        """Test case for get_collections

        Get list of existing collections  # noqa: E501
        """
        pass

    def test_update_collections(self):
        """Test case for update_collections

        Perform update operation on collections  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
