# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.point_ops_any_of1_delete_points import PointOpsAnyOf1DeletePoints
globals()['PointOpsAnyOf1DeletePoints'] = PointOpsAnyOf1DeletePoints
from openapi_client.model.point_ops_any_of1 import PointOpsAnyOf1


class TestPointOpsAnyOf1(unittest.TestCase):
    """PointOpsAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointOpsAnyOf1(self):
        """Test PointOpsAnyOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointOpsAnyOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
