# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.storage_ops_any_of2_change_aliases import StorageOpsAnyOf2ChangeAliases
globals()['StorageOpsAnyOf2ChangeAliases'] = StorageOpsAnyOf2ChangeAliases
from openapi_client.model.storage_ops_any_of2 import StorageOpsAnyOf2


class TestStorageOpsAnyOf2(unittest.TestCase):
    """StorageOpsAnyOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageOpsAnyOf2(self):
        """Test StorageOpsAnyOf2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageOpsAnyOf2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
